/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.43.1.0
 *
 * Project: 'smart_parking_barrier' 
 * Target:  'Target_1' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H

/* Keil::Device:CubeMX@1.0.0 */
#define RTE_DEVICE_CUBE_MX
#define CMSIS_device_header "stm32f4xx.h"
/* Keil::File System&MDK:CORE@8.0.2 */
#define RTE_FileSystem_Core             /* File System Core */
/* Keil::Network&MDK:CORE@8.1.0 */
#define RTE_Network_Core                /* Network Core */
/* Keil::USB&MDK:CORE@8.0.0 */
#define RTE_USB_Core                    /* USB Core */


#endif /* RTE_COMPONENTS_H */
